---
- name: Check if template exists
  ovirt_template_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ template_name }} and datacenter={{ template_cluster }}"
  register: template_info

- name: Create oVirt image template
  include_role:
    name: ovirt.image-template
  when: template_info.ovirt_templates | length == 0

- name: Debug
  debug:
    msg: "{{ template_info }}"

- name: Set template id
  set_fact:
    template_id: "{{ template_info.ovirt_templates[0].id}}"

- name: Debug
  debug:
    msg: "{{ template_id }}"

- name: Set password for template
  ovirt_template:
    auth: "{{ ovirt_auth }}"
    id: "{{template_id}}"
    cloud_init:
      root_password: "123456"
      user_name: "root"