 - name: Debugging
   debug:
     msg : "{{vm_name}}"

 - name: Initialize Pg-bench vm
   ovirt_vms:
     auth: "{{ ovirt_auth }}"
     template: "{{template_name}}"
     cluster: "{{template_cluster}}"
     name: "{{vm_name}}"
     state: running
     wait: true