---
    - name: Drop the database if exists
      command: mysql -u root -p"{{ mysql_root_password }}" -e "DROP DATABASE IF EXISTS sbtest"

    - name: Create the sbtest table
      command: mysqladmin -u root -p"{{ mysql_root_password }}" create sbtest

    - name: Populating the DB
      command: sysbench --db-driver=mysql --mysql-user=root --mysql-password="{{ mysql_root_password }}"  --mysql-db=sbtest --table_size="{{ sysbench_table_size }}" --tables="{{ sysbench_number_of_table }}"  /usr/share/sysbench/oltp_read_write.lua prepare
...
