---

- name: Setup  stats collection folder
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items: "{{host_folders}}"
  tags:
    - set_hosts_collection_folders
