---
    - name: Setup MariaDB repo
      template:
          src: mariadb.repo.j2
          dest: /etc/yum.repos.d/mariadb.repo

    - name: Install MariaDB package
      shell: yum install MariaDB-server MariaDB-devel -y

    - name: Setup Sysbench repo
      shell: curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh | sudo bash

    - name: Install Sysbench package
      shell: yum install sysbench -y

    - name: Start MySQL Service
      service:
          name: mysql
          state: started

    - name: Change Selinux Policy to Permissive
      selinux:
          policy: targeted
          state: permissive

    - name: Get Selinux
      shell: getenforce
      register: reg_var

    - name: Debug Selinux
      debug:
          msg: "{{ reg_var.stdout }}"

    - name: Creating XFS filesystem on the data disk
      filesystem:
          fstype: xfs
          dev: "{{ disk_name }}"

    - name: Create Perf1 Directory
      file:
        path=/perf1
        state=directory


    - name: Adding an entry to /etc/fstab for the data disk
      mount:
          path: /perf1
          src: "{{ disk_name }}"
          fstype: xfs
          state: present

    - name: Mounting the data disk on the mount point
      command: mount -a
      remote_user: root
      become: yes
      become_method: sudo

    - name: Create innodb data dir
      file:
          path: /perf1/mysql_data
          state: directory

    - name: Change Permissions of mysql_data
      shell: chmod 777 /perf1/mysql_data

    - name: Stop MySQL Service
      service:
          name: mysql
          state: stopped

    - name: Move MySQL directory on Data Disk
      command: mv /var/lib/mysql /perf1/

    - name: Create symlink from Data Disk on to OS
      command: ln -sf  /perf1/mysql /var/lib/mysql

    - name: Start MySQL Service
      service:
          name: mysql
          state: started

    - name: Stop MySQL Service
      service:
          name: mysql
          state: stopped

    - name: Copy MariDB Configuration file
      template:
          src: my.cnf.j2
          dest: /etc/my.cnf

    - name: Start MySQL Service
      service:
          name: mysql
          state: started

    - name: Set root password
      command: mysqladmin -u root password "{{ mysql_root_password }}"
...
